/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package customer;

/**
 *
 * @author chatw
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlaceOrder = new javax.swing.JPanel();
        makePurchesPanel = new javax.swing.JPanel();
        txtTotPrice = new javax.swing.JLabel();
        btnSendOrder = new javax.swing.JButton();
        btnCancelOrder = new javax.swing.JButton();
        txtTot = new javax.swing.JLabel();
        txtLine2 = new javax.swing.JLabel();
        AdditionalInfo = new javax.swing.JPanel();
        txtAdditionalInfo = new javax.swing.JLabel();
        txtline = new javax.swing.JLabel();
        scrAdditionalInfo = new javax.swing.JScrollPane();
        inputTxtAdditionalInfo = new javax.swing.JTextArea();
        ItemPanel2 = new javax.swing.JPanel();
        picItem2 = new javax.swing.JLabel();
        txtSalad2 = new javax.swing.JLabel();
        txtPrice2 = new javax.swing.JLabel();
        btnRemove2 = new javax.swing.JButton();
        txtQty2 = new javax.swing.JLabel();
        btnAdd2 = new javax.swing.JButton();
        ItemPanel1 = new javax.swing.JPanel();
        picItem1 = new javax.swing.JLabel();
        txtSalad1 = new javax.swing.JLabel();
        txtPrice1 = new javax.swing.JLabel();
        btnRemove1 = new javax.swing.JButton();
        txtQty1 = new javax.swing.JLabel();
        btnAdd1 = new javax.swing.JButton();
        ItemPanel = new javax.swing.JPanel();
        picItem = new javax.swing.JLabel();
        txtSalad = new javax.swing.JLabel();
        txtPrice = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();
        txtQty = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        ItemPanel4 = new javax.swing.JPanel();
        picItem4 = new javax.swing.JLabel();
        txtSalad4 = new javax.swing.JLabel();
        txtPrice4 = new javax.swing.JLabel();
        btnRemove4 = new javax.swing.JButton();
        txtQty4 = new javax.swing.JLabel();
        btnAdd4 = new javax.swing.JButton();
        ItemPanel5 = new javax.swing.JPanel();
        picItem5 = new javax.swing.JLabel();
        txtSalad5 = new javax.swing.JLabel();
        txtPrice5 = new javax.swing.JLabel();
        btnRemove5 = new javax.swing.JButton();
        txtQty5 = new javax.swing.JLabel();
        btnAdd5 = new javax.swing.JButton();
        BackgroundImage2 = new javax.swing.JLabel();
        PickSeat = new javax.swing.JPanel();
        btnT3 = new javax.swing.JButton();
        btnT4 = new javax.swing.JButton();
        btnT2 = new javax.swing.JButton();
        btnT5 = new javax.swing.JButton();
        btnT1 = new javax.swing.JButton();
        btnT6 = new javax.swing.JButton();
        btnT7 = new javax.swing.JButton();
        btnT8 = new javax.swing.JButton();
        btnT9 = new javax.swing.JButton();
        btnT10 = new javax.swing.JButton();
        btnT11 = new javax.swing.JButton();
        btnT12 = new javax.swing.JButton();
        btnT13 = new javax.swing.JButton();
        btnT14 = new javax.swing.JButton();
        btnT15 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BackgroundImage1 = new javax.swing.JLabel();
        pickMenu = new javax.swing.JPanel();
        btnTrackOrder = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        BackgroundImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        PlaceOrder.setLayout(null);

        makePurchesPanel.setBackground(new java.awt.Color(255, 255, 255));
        makePurchesPanel.setForeground(new java.awt.Color(169, 169, 169));
        makePurchesPanel.setLayout(null);

        txtTotPrice.setBackground(new java.awt.Color(0, 0, 0));
        txtTotPrice.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        txtTotPrice.setForeground(new java.awt.Color(0, 0, 0));
        txtTotPrice.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTotPrice.setText("Rs 0");
        makePurchesPanel.add(txtTotPrice);
        txtTotPrice.setBounds(180, 10, 150, 60);

        btnSendOrder.setBackground(new java.awt.Color(229, 178, 0));
        btnSendOrder.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnSendOrder.setForeground(new java.awt.Color(0, 0, 0));
        btnSendOrder.setText("SEND ORDER");
        btnSendOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendOrderActionPerformed(evt);
            }
        });
        makePurchesPanel.add(btnSendOrder);
        btnSendOrder.setBounds(190, 120, 160, 60);

        btnCancelOrder.setBackground(new java.awt.Color(214, 55, 55));
        btnCancelOrder.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnCancelOrder.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelOrder.setText("CANCEL ORDER");
        btnCancelOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelOrderActionPerformed(evt);
            }
        });
        makePurchesPanel.add(btnCancelOrder);
        btnCancelOrder.setBounds(20, 120, 160, 60);

        txtTot.setBackground(new java.awt.Color(0, 0, 0));
        txtTot.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        txtTot.setForeground(new java.awt.Color(0, 0, 0));
        txtTot.setText("TOTAL");
        makePurchesPanel.add(txtTot);
        txtTot.setBounds(10, 10, 130, 60);

        txtLine2.setBackground(new java.awt.Color(144, 144, 144));
        txtLine2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtLine2.setText("-----------------------------------------------------------------");
        makePurchesPanel.add(txtLine2);
        txtLine2.setBounds(0, 80, 370, 20);

        PlaceOrder.add(makePurchesPanel);
        makePurchesPanel.setBounds(690, 380, 370, 210);

        AdditionalInfo.setBackground(new java.awt.Color(255, 255, 255));
        AdditionalInfo.setLayout(null);

        txtAdditionalInfo.setBackground(new java.awt.Color(0, 0, 0));
        txtAdditionalInfo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 24)); // NOI18N
        txtAdditionalInfo.setForeground(new java.awt.Color(0, 0, 0));
        txtAdditionalInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAdditionalInfo.setText("ADDITIONAL INFO");
        AdditionalInfo.add(txtAdditionalInfo);
        txtAdditionalInfo.setBounds(30, 10, 290, 60);

        txtline.setBackground(new java.awt.Color(144, 144, 144));
        txtline.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtline.setText("-----------------------------------------------------------------");
        AdditionalInfo.add(txtline);
        txtline.setBounds(0, 60, 370, 20);

        scrAdditionalInfo.setBackground(new java.awt.Color(255, 255, 255));

        inputTxtAdditionalInfo.setBackground(new java.awt.Color(255, 255, 255));
        inputTxtAdditionalInfo.setColumns(20);
        inputTxtAdditionalInfo.setForeground(new java.awt.Color(0, 0, 0));
        inputTxtAdditionalInfo.setRows(5);
        scrAdditionalInfo.setViewportView(inputTxtAdditionalInfo);

        AdditionalInfo.add(scrAdditionalInfo);
        scrAdditionalInfo.setBounds(10, 80, 340, 170);

        PlaceOrder.add(AdditionalInfo);
        AdditionalInfo.setBounds(690, 70, 360, 260);

        ItemPanel2.setBackground(new java.awt.Color(255, 255, 255));
        ItemPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        ItemPanel2.setForeground(new java.awt.Color(169, 169, 169));
        ItemPanel2.setLayout(null);

        picItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/saladIcon.png"))); // NOI18N
        ItemPanel2.add(picItem2);
        picItem2.setBounds(10, 10, 50, 50);

        txtSalad2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtSalad2.setForeground(new java.awt.Color(0, 0, 0));
        txtSalad2.setText("SALAD");
        ItemPanel2.add(txtSalad2);
        txtSalad2.setBounds(80, 20, 100, 16);

        txtPrice2.setBackground(new java.awt.Color(0, 0, 0));
        txtPrice2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtPrice2.setForeground(new java.awt.Color(0, 0, 0));
        txtPrice2.setText("Rs 300");
        ItemPanel2.add(txtPrice2);
        txtPrice2.setBounds(80, 40, 34, 16);

        btnRemove2.setBackground(new java.awt.Color(51, 51, 51));
        btnRemove2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRemove2.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove2.setText("-");
        btnRemove2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemove2ActionPerformed(evt);
            }
        });
        ItemPanel2.add(btnRemove2);
        btnRemove2.setBounds(370, 10, 50, 50);

        txtQty2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        txtQty2.setForeground(new java.awt.Color(0, 0, 0));
        txtQty2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtQty2.setText("0");
        ItemPanel2.add(txtQty2);
        txtQty2.setBounds(320, 10, 50, 50);

        btnAdd2.setBackground(new java.awt.Color(51, 51, 51));
        btnAdd2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdd2.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd2.setText("+");
        ItemPanel2.add(btnAdd2);
        btnAdd2.setBounds(270, 10, 50, 50);

        PlaceOrder.add(ItemPanel2);
        ItemPanel2.setBounds(60, 260, 440, 70);

        ItemPanel1.setBackground(new java.awt.Color(255, 255, 255));
        ItemPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        ItemPanel1.setForeground(new java.awt.Color(169, 169, 169));
        ItemPanel1.setLayout(null);

        picItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/saladIcon.png"))); // NOI18N
        ItemPanel1.add(picItem1);
        picItem1.setBounds(10, 10, 50, 50);

        txtSalad1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtSalad1.setForeground(new java.awt.Color(0, 0, 0));
        txtSalad1.setText("SALAD");
        ItemPanel1.add(txtSalad1);
        txtSalad1.setBounds(80, 20, 100, 16);

        txtPrice1.setBackground(new java.awt.Color(0, 0, 0));
        txtPrice1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtPrice1.setForeground(new java.awt.Color(0, 0, 0));
        txtPrice1.setText("Rs 300");
        ItemPanel1.add(txtPrice1);
        txtPrice1.setBounds(80, 40, 34, 16);

        btnRemove1.setBackground(new java.awt.Color(51, 51, 51));
        btnRemove1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRemove1.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove1.setText("-");
        btnRemove1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemove1ActionPerformed(evt);
            }
        });
        ItemPanel1.add(btnRemove1);
        btnRemove1.setBounds(370, 10, 50, 50);

        txtQty1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        txtQty1.setForeground(new java.awt.Color(0, 0, 0));
        txtQty1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtQty1.setText("0");
        ItemPanel1.add(txtQty1);
        txtQty1.setBounds(320, 10, 50, 50);

        btnAdd1.setBackground(new java.awt.Color(51, 51, 51));
        btnAdd1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdd1.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd1.setText("+");
        ItemPanel1.add(btnAdd1);
        btnAdd1.setBounds(270, 10, 50, 50);

        PlaceOrder.add(ItemPanel1);
        ItemPanel1.setBounds(60, 170, 440, 70);

        ItemPanel.setBackground(new java.awt.Color(255, 255, 255));
        ItemPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        ItemPanel.setForeground(new java.awt.Color(169, 169, 169));
        ItemPanel.setLayout(null);

        picItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/saladIcon.png"))); // NOI18N
        ItemPanel.add(picItem);
        picItem.setBounds(10, 10, 50, 50);

        txtSalad.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtSalad.setForeground(new java.awt.Color(0, 0, 0));
        txtSalad.setText("SALAD");
        ItemPanel.add(txtSalad);
        txtSalad.setBounds(80, 20, 100, 16);

        txtPrice.setBackground(new java.awt.Color(0, 0, 0));
        txtPrice.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtPrice.setForeground(new java.awt.Color(0, 0, 0));
        txtPrice.setText("Rs 300");
        ItemPanel.add(txtPrice);
        txtPrice.setBounds(80, 40, 34, 16);

        btnRemove.setBackground(new java.awt.Color(51, 51, 51));
        btnRemove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRemove.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove.setText("-");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        ItemPanel.add(btnRemove);
        btnRemove.setBounds(370, 10, 50, 50);

        txtQty.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        txtQty.setForeground(new java.awt.Color(0, 0, 0));
        txtQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtQty.setText("0");
        ItemPanel.add(txtQty);
        txtQty.setBounds(320, 10, 50, 50);

        btnAdd.setBackground(new java.awt.Color(51, 51, 51));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("+");
        ItemPanel.add(btnAdd);
        btnAdd.setBounds(270, 10, 50, 50);

        PlaceOrder.add(ItemPanel);
        ItemPanel.setBounds(60, 70, 440, 70);

        ItemPanel4.setBackground(new java.awt.Color(255, 255, 255));
        ItemPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        ItemPanel4.setForeground(new java.awt.Color(169, 169, 169));
        ItemPanel4.setLayout(null);

        picItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/saladIcon.png"))); // NOI18N
        ItemPanel4.add(picItem4);
        picItem4.setBounds(10, 10, 50, 50);

        txtSalad4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtSalad4.setForeground(new java.awt.Color(0, 0, 0));
        txtSalad4.setText("SALAD");
        ItemPanel4.add(txtSalad4);
        txtSalad4.setBounds(80, 20, 100, 16);

        txtPrice4.setBackground(new java.awt.Color(0, 0, 0));
        txtPrice4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtPrice4.setForeground(new java.awt.Color(0, 0, 0));
        txtPrice4.setText("Rs 300");
        ItemPanel4.add(txtPrice4);
        txtPrice4.setBounds(80, 40, 34, 16);

        btnRemove4.setBackground(new java.awt.Color(51, 51, 51));
        btnRemove4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRemove4.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove4.setText("-");
        btnRemove4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemove4ActionPerformed(evt);
            }
        });
        ItemPanel4.add(btnRemove4);
        btnRemove4.setBounds(370, 10, 50, 50);

        txtQty4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        txtQty4.setForeground(new java.awt.Color(0, 0, 0));
        txtQty4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtQty4.setText("0");
        ItemPanel4.add(txtQty4);
        txtQty4.setBounds(320, 10, 50, 50);

        btnAdd4.setBackground(new java.awt.Color(51, 51, 51));
        btnAdd4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdd4.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd4.setText("+");
        ItemPanel4.add(btnAdd4);
        btnAdd4.setBounds(270, 10, 50, 50);

        PlaceOrder.add(ItemPanel4);
        ItemPanel4.setBounds(60, 440, 440, 70);

        ItemPanel5.setBackground(new java.awt.Color(255, 255, 255));
        ItemPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));
        ItemPanel5.setForeground(new java.awt.Color(169, 169, 169));
        ItemPanel5.setLayout(null);

        picItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/saladIcon.png"))); // NOI18N
        ItemPanel5.add(picItem5);
        picItem5.setBounds(10, 10, 50, 50);

        txtSalad5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtSalad5.setForeground(new java.awt.Color(0, 0, 0));
        txtSalad5.setText("SALAD");
        ItemPanel5.add(txtSalad5);
        txtSalad5.setBounds(80, 20, 100, 16);

        txtPrice5.setBackground(new java.awt.Color(0, 0, 0));
        txtPrice5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        txtPrice5.setForeground(new java.awt.Color(0, 0, 0));
        txtPrice5.setText("Rs 300");
        ItemPanel5.add(txtPrice5);
        txtPrice5.setBounds(80, 40, 34, 16);

        btnRemove5.setBackground(new java.awt.Color(51, 51, 51));
        btnRemove5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnRemove5.setForeground(new java.awt.Color(255, 255, 255));
        btnRemove5.setText("-");
        btnRemove5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemove5ActionPerformed(evt);
            }
        });
        ItemPanel5.add(btnRemove5);
        btnRemove5.setBounds(370, 10, 50, 50);

        txtQty5.setFont(new java.awt.Font("Segoe UI Semibold", 0, 30)); // NOI18N
        txtQty5.setForeground(new java.awt.Color(0, 0, 0));
        txtQty5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtQty5.setText("0");
        ItemPanel5.add(txtQty5);
        txtQty5.setBounds(320, 10, 50, 50);

        btnAdd5.setBackground(new java.awt.Color(51, 51, 51));
        btnAdd5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdd5.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd5.setText("+");
        ItemPanel5.add(btnAdd5);
        btnAdd5.setBounds(270, 10, 50, 50);

        PlaceOrder.add(ItemPanel5);
        ItemPanel5.setBounds(60, 350, 440, 70);

        BackgroundImage2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/Background.png"))); // NOI18N
        PlaceOrder.add(BackgroundImage2);
        BackgroundImage2.setBounds(0, 0, 1067, 612);

        getContentPane().add(PlaceOrder);
        PlaceOrder.setBounds(0, 0, 1070, 610);

        PickSeat.setLayout(null);

        btnT3.setBackground(new java.awt.Color(234, 240, 240));
        btnT3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnT3.setForeground(new java.awt.Color(0, 0, 0));
        btnT3.setText("TC");
        PickSeat.add(btnT3);
        btnT3.setBounds(520, 190, 90, 70);

        btnT4.setBackground(new java.awt.Color(234, 240, 240));
        btnT4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnT4.setForeground(new java.awt.Color(0, 0, 0));
        btnT4.setText("TD");
        btnT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnT4ActionPerformed(evt);
            }
        });
        PickSeat.add(btnT4);
        btnT4.setBounds(670, 190, 90, 70);

        btnT2.setBackground(new java.awt.Color(234, 240, 240));
        btnT2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnT2.setForeground(new java.awt.Color(0, 0, 0));
        btnT2.setText("TB");
        PickSeat.add(btnT2);
        btnT2.setBounds(370, 190, 90, 70);

        btnT5.setBackground(new java.awt.Color(234, 240, 240));
        btnT5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnT5.setForeground(new java.awt.Color(0, 0, 0));
        btnT5.setText("TE");
        PickSeat.add(btnT5);
        btnT5.setBounds(810, 190, 90, 70);

        btnT1.setBackground(new java.awt.Color(234, 240, 240));
        btnT1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnT1.setForeground(new java.awt.Color(0, 0, 0));
        btnT1.setText("TA");
        PickSeat.add(btnT1);
        btnT1.setBounds(220, 190, 90, 70);

        btnT6.setBackground(new java.awt.Color(234, 240, 240));
        btnT6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnT6.setForeground(new java.awt.Color(0, 0, 0));
        btnT6.setText("TJ");
        PickSeat.add(btnT6);
        btnT6.setBounds(810, 290, 90, 70);

        btnT7.setBackground(new java.awt.Color(234, 240, 240));
        btnT7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnT7.setForeground(new java.awt.Color(0, 0, 0));
        btnT7.setText("TH");
        btnT7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnT7ActionPerformed(evt);
            }
        });
        PickSeat.add(btnT7);
        btnT7.setBounds(520, 290, 90, 70);

        btnT8.setBackground(new java.awt.Color(234, 240, 240));
        btnT8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnT8.setForeground(new java.awt.Color(0, 0, 0));
        btnT8.setText("TG");
        PickSeat.add(btnT8);
        btnT8.setBounds(370, 290, 90, 70);

        btnT9.setBackground(new java.awt.Color(234, 240, 240));
        btnT9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnT9.setForeground(new java.awt.Color(0, 0, 0));
        btnT9.setText("TI");
        PickSeat.add(btnT9);
        btnT9.setBounds(670, 290, 90, 70);

        btnT10.setBackground(new java.awt.Color(234, 240, 240));
        btnT10.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnT10.setForeground(new java.awt.Color(0, 0, 0));
        btnT10.setText("TF");
        btnT10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnT10ActionPerformed(evt);
            }
        });
        PickSeat.add(btnT10);
        btnT10.setBounds(220, 290, 90, 70);

        btnT11.setBackground(new java.awt.Color(234, 240, 240));
        btnT11.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnT11.setForeground(new java.awt.Color(0, 0, 0));
        btnT11.setText("TL");
        PickSeat.add(btnT11);
        btnT11.setBounds(370, 390, 90, 70);

        btnT12.setBackground(new java.awt.Color(234, 240, 240));
        btnT12.setFont(new java.awt.Font("Segoe UI", 1, 34)); // NOI18N
        btnT12.setForeground(new java.awt.Color(0, 0, 0));
        btnT12.setText("TN");
        PickSeat.add(btnT12);
        btnT12.setBounds(670, 390, 90, 70);

        btnT13.setBackground(new java.awt.Color(234, 240, 240));
        btnT13.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        btnT13.setForeground(new java.awt.Color(0, 0, 0));
        btnT13.setText("TK");
        PickSeat.add(btnT13);
        btnT13.setBounds(220, 390, 90, 70);

        btnT14.setBackground(new java.awt.Color(234, 240, 240));
        btnT14.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        btnT14.setForeground(new java.awt.Color(0, 0, 0));
        btnT14.setText("TM");
        PickSeat.add(btnT14);
        btnT14.setBounds(520, 390, 90, 70);

        btnT15.setBackground(new java.awt.Color(234, 240, 240));
        btnT15.setFont(new java.awt.Font("Segoe UI", 1, 32)); // NOI18N
        btnT15.setForeground(new java.awt.Color(0, 0, 0));
        btnT15.setText("TO");
        PickSeat.add(btnT15);
        btnT15.setBounds(810, 390, 90, 70);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SELECT TABLE");
        PickSeat.add(jLabel1);
        jLabel1.setBounds(380, 70, 340, 40);

        BackgroundImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/Background.png"))); // NOI18N
        PickSeat.add(BackgroundImage1);
        BackgroundImage1.setBounds(0, 0, 1067, 612);

        getContentPane().add(PickSeat);
        PickSeat.setBounds(0, 0, 1070, 610);

        pickMenu.setLayout(null);

        btnTrackOrder.setBackground(new java.awt.Color(244, 119, 0));
        btnTrackOrder.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnTrackOrder.setForeground(new java.awt.Color(249, 249, 249));
        btnTrackOrder.setText("TRACK ORDER");
        pickMenu.add(btnTrackOrder);
        btnTrackOrder.setBounds(600, 140, 330, 420);

        btnOrder.setBackground(new java.awt.Color(229, 178, 0));
        btnOrder.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(249, 249, 249));
        btnOrder.setText("ORDER FOODS");
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });
        pickMenu.add(btnOrder);
        btnOrder.setBounds(150, 140, 330, 420);

        BackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/customer/Background.png"))); // NOI18N
        pickMenu.add(BackgroundImage);
        BackgroundImage.setBounds(0, 0, 1067, 612);

        getContentPane().add(pickMenu);
        pickMenu.setBounds(0, 0, 1070, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        pickMenu.setVisible(false);
        
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnT4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnT4ActionPerformed

    private void btnT10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnT10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnT10ActionPerformed

    private void btnT7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnT7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnT7ActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void btnRemove1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemove1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemove1ActionPerformed

    private void btnRemove2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemove2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemove2ActionPerformed

    private void btnRemove4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemove4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemove4ActionPerformed

    private void btnRemove5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemove5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRemove5ActionPerformed

    private void btnSendOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendOrderActionPerformed

    private void btnCancelOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdditionalInfo;
    private javax.swing.JLabel BackgroundImage;
    private javax.swing.JLabel BackgroundImage1;
    private javax.swing.JLabel BackgroundImage2;
    private javax.swing.JPanel ItemPanel;
    private javax.swing.JPanel ItemPanel1;
    private javax.swing.JPanel ItemPanel2;
    private javax.swing.JPanel ItemPanel4;
    private javax.swing.JPanel ItemPanel5;
    private javax.swing.JPanel PickSeat;
    private javax.swing.JPanel PlaceOrder;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnAdd2;
    private javax.swing.JButton btnAdd4;
    private javax.swing.JButton btnAdd5;
    private javax.swing.JButton btnCancelOrder;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnRemove1;
    private javax.swing.JButton btnRemove2;
    private javax.swing.JButton btnRemove4;
    private javax.swing.JButton btnRemove5;
    private javax.swing.JButton btnSendOrder;
    private javax.swing.JButton btnT1;
    private javax.swing.JButton btnT10;
    private javax.swing.JButton btnT11;
    private javax.swing.JButton btnT12;
    private javax.swing.JButton btnT13;
    private javax.swing.JButton btnT14;
    private javax.swing.JButton btnT15;
    private javax.swing.JButton btnT2;
    private javax.swing.JButton btnT3;
    private javax.swing.JButton btnT4;
    private javax.swing.JButton btnT5;
    private javax.swing.JButton btnT6;
    private javax.swing.JButton btnT7;
    private javax.swing.JButton btnT8;
    private javax.swing.JButton btnT9;
    private javax.swing.JButton btnTrackOrder;
    private javax.swing.JTextArea inputTxtAdditionalInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel makePurchesPanel;
    private javax.swing.JLabel picItem;
    private javax.swing.JLabel picItem1;
    private javax.swing.JLabel picItem2;
    private javax.swing.JLabel picItem4;
    private javax.swing.JLabel picItem5;
    private javax.swing.JPanel pickMenu;
    private javax.swing.JScrollPane scrAdditionalInfo;
    private javax.swing.JLabel txtAdditionalInfo;
    private javax.swing.JLabel txtLine2;
    private javax.swing.JLabel txtPrice;
    private javax.swing.JLabel txtPrice1;
    private javax.swing.JLabel txtPrice2;
    private javax.swing.JLabel txtPrice4;
    private javax.swing.JLabel txtPrice5;
    private javax.swing.JLabel txtQty;
    private javax.swing.JLabel txtQty1;
    private javax.swing.JLabel txtQty2;
    private javax.swing.JLabel txtQty4;
    private javax.swing.JLabel txtQty5;
    private javax.swing.JLabel txtSalad;
    private javax.swing.JLabel txtSalad1;
    private javax.swing.JLabel txtSalad2;
    private javax.swing.JLabel txtSalad4;
    private javax.swing.JLabel txtSalad5;
    private javax.swing.JLabel txtTot;
    private javax.swing.JLabel txtTotPrice;
    private javax.swing.JLabel txtline;
    // End of variables declaration//GEN-END:variables
}
