/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package employee;
import database.RestaurantDatabase;
import java.util.*;

import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JScrollPane;

/**
 *
 * @author chatw
 */
public class OrderDetails extends javax.swing.JFrame {
    
    private JTable Orders;
    private DefaultTableModel OrdersModel;
    /**
     * Creates new form OrderDetails
     */
    public OrderDetails() {
        initComponents();
        setupTable();

    }
        private void setupTable() {
        // Initialize the table model
        OrdersModel = new DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Table ID", "Item", "Quantity", "Extra", "Order state", "Time & Date"
            }
        );

//        // Initialize the table
        Orders = new JTable(OrdersModel);
//
//        // Add the table to a JScrollPane and add it to your form
        JScrollPane scrollPane = new JScrollPane(Orders);
        scrollPane.setBounds(250, 100, 800, 350); // adjust these values as needed
        getContentPane().add(scrollPane);
    }
 public void getSQL() {
    List<Map<String, String>> result;
    // This is to store the SQL query
    String sql;

    RestaurantDatabase db = new RestaurantDatabase();

    // SQL query to get all orders with currentState = "pending", and their corresponding food item name, ordered quantity, table ID, order date, order time, and current state
    sql = "SELECT o.orderId, o.TableId, o.orderdDate, o.orderdTime, o.currentState,o.additionalInfo, f.foodName, orderFood.quntity " +
          "FROM `order` o " +
          "JOIN `orderFood` ON o.orderId = `orderFood`.orderId " +
          "JOIN food f ON `orderFood`.foodId = f.foodId " +
          "WHERE o.currentState = 'pending';";

    result = db.executeQuery(sql);
    System.out.println(result);

    try {
        db.getConnection().close();
    } catch (Exception e) {
        System.out.println("Error while closing the connection: " + e.getMessage());
    }
    for (Map<String, String> row : result) {
        OrdersModel.addRow(new Object[] {
            row.get("orderId"),
            row.get("TableId"),
            row.get("foodName"),
            row.get("quntity"),
            row.get("additionalInfo"),
            row.get("currentState"),
            row.get("orderdTime") // Time & Date
        });
    }

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbOrderId = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnFinish1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1100, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        cmbOrderId.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cmbOrderId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Order ID" }));
        cmbOrderId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbOrderIdActionPerformed(evt);
            }
        });
        getContentPane().add(cmbOrderId);
        cmbOrderId.setBounds(250, 480, 207, 40);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jButton1.setText("TAKE ORDER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(470, 480, 175, 40);

        btnCancel.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnCancel.setText("CANCEL ORDER");
        getContentPane().add(btnCancel);
        btnCancel.setBounds(660, 480, 179, 40);

        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset);
        btnReset.setBounds(860, 20, 175, 40);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ORDER");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(230, 10, 130, 59);

        btnFinish1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        btnFinish1.setText("FINISH ORDER");
        getContentPane().add(btnFinish1);
        btnFinish1.setBounds(850, 480, 175, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbOrderIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbOrderIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbOrderIdActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        getSQL();
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderDetails().setVisible(true);
            }
            
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnFinish1;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox<String> cmbOrderId;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
